homeassistant:
  name: "Beach House"
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  external_url: !secret external_url
  packages: !include_dir_named packages/
  allowlist_external_dirs:
    - /tmp

scene: !include scenes.yaml
script: !include scripts.yaml


# Configuration

api:

config:

backup:

frontend: !include config/frontend.yaml

google_assistant: !include config/google_assistant.yaml

history: !include config/history.yaml

http: !include config/http.yaml

ios:

logger: !include config/logger.yaml

lovelace: !include config/lovelace.yaml

media_source:

mobile_app:

notify: !include config/notify.yaml

panel_custom: !include config/panel_custom.yaml

recorder: !include config/recorder.yaml

stream: