title: Beach House

views:
  - title: "Home"
    path: "home"
    cards:
      - type: vertical-stack
        title: Beach House
        cards:
          # House Pic
          - type: picture-entity
            entity: camera.beach
            show_name: false
            show_state: false
            tap_action: 
              action: 'navigate'
              navigation_path: '/lovelace/cameras'
            card_mod:
              style: |
                .type-picture-entity {
                  background-color: rgb(85, 85, 85);
                  border-radius: var(--ha-card-border-radius, 4px);
                  min-height: 260px;
                  max-height: 260px;
                  transition: none;
                }
                @media only screen and (hover: none) and (pointer: coarse) {
                  .type-picture-entity {
                    min-height: 260px !important;
                  }
                }

          # Actions - Morning
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
              - entity: input_boolean.night_mode
                state: "on"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.good_morning
                  icon_height: 2.25em
                  tap_action:
                    action: call-service
                    service: script.turn_on
                    service_data:
                      entity_id: script.good_morning

          # Actions - Day and Evening
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
              - entity: input_boolean.night_mode
                state: "off"
            card:
              type: vertical-stack
              cards:
                - type: horizontal-stack
                  cards:
                    - type: entity-button
                      entity: scene.dinner_lights
                      name: "Dinner Lights"
                      icon: mdi:food-fork-drink
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.dinner_lights
                    - type: entity-button
                      entity: script.movie_lights
                      name: "Movie Time"
                      icon: mdi:movie
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.turn_on
                        service_data:
                          entity_id: script.movie_lights

                - type: horizontal-stack
                  cards:
                    - type: entity-button
                      entity: scene.mood_lights
                      name: Mood Lights
                      icon: mdi:movie
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.mood_lights
                    - type: entity-button
                      entity: script.good_night
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.turn_on
                        service_data:
                          entity_id: script.good_night

          - type: vertical-stack
            title: "Status"
            cards:
              - type: markdown
                entity_id:
                  - sensor.dark_sky_temperature
                  - sensor.dark_sky_hourly_summary
                  - sensor.tides
                  - sensor.water_temp
                  - alarm_control_panel.abode_alarm
                content: >
                  <ha-icon icon="mdi:weather-sunny"></ha-icon> Currently {{ states('sensor.dark_sky_temperature')|round(0) }}°. {{ states('sensor.dark_sky_hourly_summary') }}


                  <ha-icon icon="mdi:waves"></ha-icon> {{ states('sensor.tides') }} of {{ (state_attr('sensor.tides', 'low_tide_level') or state_attr('sensor.tides', 'high_tide_level'))|round(1) }}'. Water is {{ states('sensor.water_temp')|round(0) }} {{ state_attr('sensor.water_temp', 'unit_of_measurement') }}.


                  {% if is_state('alarm_control_panel.abode_alarm', 'armed_home') %}

                    <ha-icon icon="mdi:shield-home-outline"></ha-icon> Alarm is armed home
                  {% elif is_state('alarm_control_panel.abode_alarm', 'armed_away') %}

                    <ha-icon icon="mdi:shield-lock-outline"></ha-icon> Alarm is armed away
                  {% endif %}

              - type: entity-filter
                card:
                  type: entities
                  show_header_toggle: false
                state_filter:
                  - "on"
                show_empty: false
                entities:
                  - entity: binary_sensor.front_door
                    icon: mdi:door
                  - entity: binary_sensor.kitchen_door
                    icon: mdi:door
                  - entity: binary_sensor.kitchen_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.bay_window_left
                    icon: mdi:window-closed
                  - entity: binary_sensor.bay_window_right
                    icon: mdi:window-closed
                  - entity: binary_sensor.bathroom_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.driveway_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.downstairs_front_window_left
                    icon: mdi:window-closed
                  - entity: binary_sensor.downstairs_front_window_right
                    icon: mdi:window-closed
                  - entity: binary_sensor.master_slider
                    icon: mdi:door

  - title: "Inside"
    path: "inside"
    cards:
      - type: entities
        title: "Lights"
        show_header_toggle: true
        state_color: true
        entities:
          - entity: light.living_room
          - entity: light.dining_table
          - entity: light.kitchen_lights
          - entity: light.kitchen_cabinets
          - entity: light.kitchen_sink
          - entity: switch.desk
          - entity: light.recessed
          - entity: light.picture
          - entity: light.hallway
          - entity: light.guest_bed
          - entity: light.bunk_bed
          - entity: light.master_bedroom
          - entity: light.master_wall

      - type: entities
        title: "Media"
        show_header_toggle: false
        state_color: true
        entities:
          - entity: media_player.living_room_tv
          - entity: media_player.master_tv
          - entity: media_player.bunk_bedroom_tv

      - type: entities
        title: "Climate"
        show_header_toggle: false
        state_color: true
        entities:
          - entity: climate.downstairs
            type: custom:multiple-entity-row
            show_state: false
            state_color: false
            entities:
              - entity: sensor.downstairs_temp
                name: "Temperature"
              - entity: climate.downstairs
                name: "Mode"
          - entity: climate.upstairs
            type: custom:multiple-entity-row
            show_state: false
            state_color: false
            entities:
              - entity: sensor.upstairs_temp
                name: "Temperature"
              - entity: climate.upstairs
                name: "Mode"
          - entity: climate.bathroom_floor
            type: custom:multiple-entity-row
            icon: mdi:radiator
            show_state: false
            state_color: false
            entities:
              - entity: sensor.bathroom_floor_temp
                name: "Temperature"
              - entity: climate.bathroom_floor
                name: "Mode"
          - type: section
          - entity: automation.climate_windows_open
            state_color: false
            name: Turn off when windows open

  - title: "Outside"
    path: "outside"
    cards:
      - type: glance
        title: "Weather"
        show_name: false
        entities:
          - entity: sensor.dark_sky_temperature
          - entity: sensor.dark_sky_humidity
          - entity: sensor.dark_sky_wind_speed
          - entity: sensor.dark_sky_uv_index

      - type: entities
        title: "Windows"
        entities:
          - entity: group.shades
            type: custom:multiple-entity-row
            name: Shades
            icon: mdi:grid-large
            show_state: false
            entities:
              - icon: mdi:arrow-up
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.shades_up
              - icon: mdi:stop
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.shades_halfway
              - icon: mdi:arrow-down
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.shades_down
              - icon: mdi:menu
                tap_action:
                  action: more-info

      - type: entities
        title: "Landscape"
        show_header_toggle: true
        state_color: true
        entities:
          - entity: switch.front_door_lights
          - entity: switch.front_deck_lights
          - entity: group.back_lights
            icon: mdi:lightbulb
          - entity: switch.back_twinkle_lights
          - entity: switch.back_stairs_light
          - entity: switch.upstairs_deck_lights

  - title: "Cameras"
    path: "cameras"
    visible: false
    cards:
      - type: grid
        title: "Live Cameras"
        square: false
        columns: 1
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.beach
          - type: picture-entity
            entity: camera.front_deck
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.driveway
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.backyard
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.upstairs_deck
            show_name: false
            show_state: false
