title: Beach House

custom_header:
  tab_indicator_color: "transparent"
  exceptions:
    - conditions:
        user_agent: "Mobile"
      config:
        compact_mode: true
        footer_mode: true
        options_hide: true
        reverse_button_direction: true
        header_css: "height: 90px;"

views:
  - title: "Home"
    cards:
      - type: vertical-stack
        title: Beach House
        cards:
          - type: 'custom:refreshable-picture-card'
            update_interval: 120
            static_picture: /local/cameras/beach.png
            style: |
              .type-custom-refreshable-picture-card {
                  overflow: hidden;
                  min-height: 212px !important;
                  max-height: 300px !important;
              }
              .type-custom-refreshable-picture-card p,
              .type-custom-refreshable-picture-card br {
                display: none;
              }
              .type-custom-refreshable-picture-card .thePic {
                width: 100% !important;
                border-radius: var(--ha-card-border-radius, 4px);
              }

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.good_morning
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.turn_on
                    service_data:
                      entity_id: script.good_morning

                - type: entity-button
                  entity: script.good_night
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.turn_on
                    service_data:
                      entity_id: script.good_night

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: scene.dinner_time
                  name: Dinner Time
                  icon: mdi:food-fork-drink
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.dinner_time

                - type: entity-button
                  entity: scene.chill_time
                  name: Chill Lights
                  icon: mdi:movie
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.chill_time

          - type: vertical-stack
            title: "Status"
            cards:
              - type: markdown
                entity_id:
                  - calendar.beach_house
                  - sensor.dark_sky_temperature
                  - sensor.dark_sky_hourly_summary
                  - sensor.tides
                  - sensor.water_temp
                  - alarm_control_panel.abode_alarm
                content: >
                  {% if is_state('calendar.beach_house', 'on') %}
                    <ha-icon icon="mdi:account-multiple"></ha-icon> {{ state_attr('calendar.beach_house', 'message') }}

                  {% endif %}
                  <ha-icon icon="mdi:weather-sunny"></ha-icon> Currently {{ states('sensor.dark_sky_temperature')|round(0) }}°. {{ states('sensor.dark_sky_hourly_summary') }}


                  <ha-icon icon="mdi:waves"></ha-icon> {{ state_attr('sensor.tides', 'next_tide_type') }} tide at {{ state_attr('sensor.tides', 'next_tide_time') }}. Water is {{ states('sensor.water_temp') }} {{ state_attr('sensor.water_temp', 'unit_of_measurement') }}.


                  {% if is_state('alarm_control_panel.abode_alarm', 'armed_home') %}

                    <ha-icon icon="mdi:shield-home-outline"></ha-icon> Alarm is armed home
                  {% elif is_state('alarm_control_panel.abode_alarm', 'armed_away') %}

                    <ha-icon icon="mdi:shield-lock-outline"></ha-icon> Alarm is armed away
                  {% endif %}

              - type: entity-filter
                card:
                  type: entities
                  show_header_toggle: false
                state_filter:
                  - "on"
                show_empty: false
                entities:
                  - entity: binary_sensor.front_door
                    icon: mdi:door
                  - entity: binary_sensor.kitchen_door
                    icon: mdi:door
                  - entity: binary_sensor.kitchen_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.bay_window_left
                    icon: mdi:window-closed
                  - entity: binary_sensor.bay_window_right
                    icon: mdi:window-closed
                  - entity: binary_sensor.bathroom_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.driveway_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.downstairs_front_window_left
                    icon: mdi:window-closed
                  - entity: binary_sensor.downstairs_front_window_right
                    icon: mdi:window-closed
                  - entity: binary_sensor.master_slider
                    icon: mdi:door


  - title: "Inside"
    cards:
      - type: entities
        title: "Lights"
        show_header_toggle: true
        state_color: true
        entities:
          - entity: light.living_room
          - entity: light.dining_lights
          - entity: light.kitchen
          - entity: light.cabinets
          - entity: light.sink
          - entity: switch.desk_light
            icon: mdi:lightbulb
          - entity: light.mood_lights
          - entity: light.picture_lights
          - entity: light.hallway
          - entity: light.guest_bedroom
          - entity: light.bunk_bedroom
          - entity: light.master
          - entity: light.master_reading_lights
          - entity: light.master_wall_lights

      - type: entities
        title: "Media"
        show_header_toggle: false
        state_color: true
        entities:
          - entity: media_player.living_room_tv
          - entity: media_player.master_tv
          - entity: media_player.bunk_bedroom_tv

      - type: entities
        title: "Climate"
        show_header_toggle: false
        state_color: true
        entities:
          - entity: climate.downstairs
            type: custom:multiple-entity-row
            show_state: false
            state_color: false
            entities:
              - entity: sensor.downstairs_temp
                name: "Temperature"
              - entity: climate.downstairs
                name: "Mode"
          - entity: climate.upstairs
            type: custom:multiple-entity-row
            show_state: false
            state_color: false
            entities:
              - entity: sensor.upstairs_temp
                name: "Temperature"
              - entity: climate.upstairs
                name: "Mode"
          - type: section
          - entity: automation.climate_windows_open
            state_color: false
            name: Turn off when windows open


  - title: "Outside"
    cards:
      - type: glance
        title: "Weather"
        show_name: false
        entities:
          - entity: sensor.dark_sky_temperature
          - entity: sensor.dark_sky_humidity
          - entity: sensor.dark_sky_wind_speed
          - entity: sensor.dark_sky_uv_index

      - type: entities
        title: "Windows"
        entities:
          - entity: group.shades
            type: custom:multiple-entity-row
            name: Shades
            icon: mdi:grid-large
            show_state: false
            entities:
              - icon: mdi:arrow-up
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.shades_up
              - icon: mdi:menu
                tap_action:
                  action: more-info
              - icon: mdi:arrow-down
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.shades_down

      - type: entities
        title: "Landscape"
        show_header_toggle: true
        state_color: true
        entities:
          - entity: switch.front_door
            icon: mdi:lightbulb
          - entity: switch.front_deck
            icon: mdi:lightbulb
          - entity: switch.twinkle_lights
            icon: mdi:lightbulb
          - entity: group.backyard_lights
            icon: mdi:lightbulb
          - entity: switch.backyard_stairs
            icon: mdi:lightbulb
          - entity: switch.upstairs_deck
            icon: mdi:lightbulb
