extra_module_url:
  - /hacsfiles/lovelace-card-mod/card-mod.js

themes:
  nocard:
    ha-card-border-width: "0"
    ha-card-border-radius: "0"
    card-background-color: "transparent"

  subview:
    #primary-background-color: "#1f3943" 
    #card-background-color: "#364d56"

    primary-background-color: "#134657" 
    card-background-color: "#17576b"


  apptheme:
    # Colors - https://github.com/home-assistant/frontend/blob/master/src/resources/ha-style.ts
    
    #primary-background-color: "#04222d" 
    #card-background-color: "#1f3943" 

    #primary-background-color: "#17576b"
    primary-background-color: "radial-gradient(circle,rgba(47, 119, 143, 1) 0%, rgba(23, 87, 107, 1) 90%, rgba(23, 87, 107, 1) 100%)" 
    card-background-color: "#134657" 
    secondary-background-color: "#CCC"

    primary-text-color: "#FFF"
    secondary-text-color: "#FFF"

    accent-color: "orange" # YES!

    # Header
    app-header-text-color: "var(--primary-text-color)"
    app-header-background-color: "#17576b"
    app-header-selection-bar-color: "transparent"
    mdc-top-app-bar-fixed-box-shadow: "none"

    # Cards
    ha-card-border-width: "1px"
    ha-card-border-radius: "8px"
    divider-color: "rgba(0, 0, 0, 0.15)"

    code-editor-background-color: "#000"

    # Icons
    state-icon-color: "#FFF"
    state-active-color: "var(--accent-color)"
    state-inactive-color: "var(--state-icon-color)"

    state-light-active-color: "var(--state-active-color)"
    state-binary_sensor-active-color: "var(--state-active-color)"
    state-cover-active-color: "var(--state-active-color)"
    state-media_player-active-color: "var(--state-active-color)"

    # CSS Overrides
    card-mod-theme: apptheme
    card-mod-root: |
      #view {
        margin-top: -20px !important;
      }

      .header {
        position: relative !important;
        top: auto !important;
        height: auto !important;
        width: auto !important;
      }

      .header .main-title {
        font-size: 1.3em;
        font-weight: bold;
      }

      @media only screen and (hover: none) and (pointer: coarse) {
        .header .main-title {
          margin-left: 10px;
        }
      }

  home:
    # Colors
    # https://github.com/home-assistant/frontend/blob/master/src/resources/ha-style.ts
    primary-background-color: "#F7F8F9"
    secondary-background-color: "#F4F5F6"
    card-background-color: "#FFF"

    primary-text-color: "#555"
    secondary-text-color: "#999"
    disabled-text-color: "#B3B3B3"

    app-header-text-color: "#fff"
    app-header-background-color: "#555"
    app-header-selection-bar-color: "transparent"
    
    divider-color: "rgba(0, 0, 0, 0.15)"
    state-icon-color: "#999"

    switch-checked-button-color: "#FFF"
    switch-unchecked-button-color: "#FFF"
    switch-checked-track-color: "#0077FF"
    switch-unchecked-track-color: "#999"

    state-cover-open-color: "var(--state-active-color)"
    state-media_player-speaker-playing-color: "var(--state-active-color)"

    # General settings
    ha-card-border-width: "1px"
    ha-card-border-radius: "4px"
    
    ha-picture-icon-button-on-color: "var(--state-active-color)"
    ha-picture-card-background-color: "rgba(0, 0, 0, 0.4)"

    # Pin header on bottom of screen for mobile
    card-mod-theme: home
    card-mod-root: |
      @media only screen and (hover: none) and (pointer: coarse) {
        #view {
          margin-top: -50px !important;
          padding-bottom: 80px !important;
        }

        .header {
          position: fixed;
          top: auto !important;
          bottom: 0;
          height: 80px;
        }
      }
