project_id: !secret google_assistant_id
service_account: !include ../google_assistant_key.json
report_state: true
expose_by_default: true
exposed_domains:
  - switch
  - light
  - script
  - scene
entity_config:
  group.back_lights:
    expose: true
  group.front_lights:
    expose: true
  switch.back_lights_right:
    expose: false
  switch.back_lights_left:
    expose: false
  light.livingroom_1:
    expose: false
  light.livingroom_2:
    expose: false
  light.master_reading_1:
    expose: false
  light.master_reading_2:
    expose: false
  switch.master_wall_outlet:
    expose: false
  scene.good_morning:
    expose: false
  script.welcome_home:
    expose: false
  script.shade1up:
    expose: false
  script.shade1down:
    expose: false
  script.shade1stop:
    expose: false
  script.shade2up:
    expose: false
  script.shade2down:
    expose: false
  script.shade2stop:
    expose: false
  script.shade3up:
    expose: false
  script.shade3down:
    expose: false
  script.shade3stop:
    expose: false
  script.shade4up:
    expose: false
  script.shade4down:
    expose: false
  script.shade4stop:
    expose: false
  script.shade5up:
    expose: false
  script.shade5down:
    expose: false
  script.shade5stop:
    expose: false