project_id: !secret google_assistant_id
service_account: !include ../google_assistant_key.json
report_state: true
expose_by_default: false

entity_config:
  light.living_room:
    expose: true
  light.dining_table:
    expose: true
  light.kitchen_lights:
    expose: true
  light.kitchen_cabinets:
    expose: true
  light.kitchen_sink:
    expose: true
  light.desk:
    expose: true
  light.recessed:
    expose: true
  light.picture:
    expose: true
  light.hallway:
    expose: true
  light.guest_bed:
    expose: true
  light.bunk_bed:
    expose: true
  light.master_bedroom:
    expose: true
  light.master_wall:
    expose: true
  light.front_yard:
    expose: true
  light.back_yard:
    expose: true
  light.twinkle_lights:
    expose: true
  light.back_stairs:
    expose: true
  light.upstairs_deck:
    expose: true
  script.dinner_lights:
    expose: true
    aliases:
      - DINNER_TIME
    room: house
  script.good_morning:
    expose: true
    room: house
  script.good_night:
    expose: true
    room: house
  script.mood_lights:
    expose: true
    room: house
  script.movie_lights:
    expose: true
    aliases:
      - MOVIE_TIME
    room: house
  script.shades_up:
    expose: true
    room: house
  script.shades_down:
    expose: true
    room: house
  script.shades_halfway:
    expose: true
    room: house