mode: yaml

resources:
  - type: module
    url: /local/community/custom-header/custom-header.js
  - type: module
    url: /local/community/lovelace-multiple-entity-row/multiple-entity-row.js
  - type: module
    url: /local/community/mini-graph-card/mini-graph-card-bundle.js 