mode: yaml

resources:
  - type: module
    url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
  - type: module
    url: /hacsfiles/lovelace-card-mod/card-mod.js
  - type: module
    url: /hacsfiles/refreshable-picture-card/refreshable-picture-card.js