- name: phones
  platform: group
  services:
    - service: mobile_app_jeffs_iphone
    - service: mobile_app_jillians_iphone

- name: downstairs
  platform: tts
  tts_service: tts.google_say
  media_player: media_player.downstairs

- name: master_bedroom
  platform: tts
  tts_service: tts.google_say
  media_player: media_player.master_bedroom_speaker