# Template alarm panel to filter alarm states in UI
alarm_control_panel:
  - platform: template
    panels:
      alarm_panel_ui:
        name: "Alarm"
        value_template: "{{ states('alarm_control_panel.alarm') }}"
        code_arm_required: false
        code_format: "no_code"
        arm_away:
          service: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.alarm
        arm_home:
          service: alarm_control_panel.alarm_arm_home
          target:
            entity_id: alarm_control_panel.alarm
        disarm:
          service: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.alarm

automation:
  - alias: "Alarm - Welcome Home"
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      from: "armed_away"
      to: "disarmed"
    action:
      - service: script.turn_on
        entity_id: script.welcome_home

  - alias: "Alarm - Goodbye"
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      to: "armed_away"
    action:
      - service: script.turn_on
        entity_id: script.goodbye

  - alias: "Alarm - Notifications"
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "armed_home"
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "armed_away"
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "disarmed"
    condition:
      condition: template
      value_template: "{{ trigger.from_state.state != 'unavailable' }}"
    action:
      - service: notify.phones
        data_template:
          title: "Beach"
          message: "Alarm is {{ states('alarm_control_panel.alarm')|replace('_', ' ') }}"
      - condition: state
        entity_id: binary_sensor.doors_and_windows
        state: "on"
      - service: notify.phones
        data_template:
          title: "Beach"
          message: >
            Warning! The following are open: 
            {%- for entity in expand("binary_sensor.doors_and_windows") -%}
              {%- if entity.state == "on" -%}
                {{ entity.name }}
                {%- if not loop.last %}, {% endif -%}
              {%- endif -%}
            {%- endfor -%}

  - alias: "Alarm - Alert"
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "triggered"
    action:
      - service: notify.phones
        data:
          title: "Beach"
          message: "Alarm alert!"
          data:
            entity_id: camera.front_door
            url: "/lovelace/cameras"
            push:
              sound:
                name: "default"
                critical: 1
                volume: 1
      - service: homeassistant.turn_on
        entity_id: light.house
      - service: script.turn_on
        entity_id: script.shades_up

  - alias: "Alarm - Are you away"
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.doors_and_windows
        to: "off"
        for: "16:00:00"
    condition:
      condition: template
      value_template: "{{ is_state('alarm_control_panel.alarm', 'disarmed') }}"
    action:
      - service: notify.phones
        data:
          title: "Beach"
          message: "Are you away? Alarm is off!"
