camera:
  - platform: local_file
    name: Latest Front Deck
    file_path: "/config/www/cameras/camera.front_deck.jpg"
  - platform: local_file
    name: Latest Driveway
    file_path: "/config/www/cameras/camera.driveway.jpg"
  - platform: local_file
    name: Latest Back Yard
    file_path: "/config/www/cameras/camera.back_yard.jpg"
  - platform: local_file
    name: Latest Upstairs Deck
    file_path: "/config/www/cameras/camera.upstairs_deck.jpg"

counter:
  camera_motion:
    name: "Camera Motion Counter"
    icon: mdi:alert
    initial: 0
    restore: True

shell_command:
  purge_camera_events: !secret purge_cameras_events_cmd

automation:
  - alias: "Cameras - Motion"
    initial_state: True
    trigger:
      - platform: webhook
        webhook_id: "camera_motion"
        local_only: True
    condition:
      condition: template
      value_template: "{{ not is_state('alarm_control_panel.alarm', 'disarmed') }}"
    action:
      # take a picture
      - service: camera.snapshot
        data:
          entity_id: "{{ trigger.json.camera }}"
          filename: "/config/www/cameras/{{ trigger.json.camera }}.jpg"
      # send a notification
      - service: notify.phones
        data:
          title: "Beach"
          message: "{{ trigger.json.name }} motion"
          data:
            entity_id: "{{ trigger.json.camera }}"
            url: "/lovelace/cameras"
      # update the counter
      - service: counter.increment
        target:
          entity_id: counter.camera_motion

  - alias: "Cameras - Reset Camera Events"
    initial_state: True
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: counter.reset
        target:
          entity_id: counter.camera_motion
      - service: shell_command.purge_camera_events