shell_command:
  purge_camera_events: !secret purge_cameras_events_cmd

input_text:
  camera_motion_prompt:
    name: "Camera Motion Prompt"
    icon: "mdi:robot"
    max: 255

input_boolean:
  camera_motion_enabled:
    name: "Camera Motion Alerts"
    icon: "mdi:robot"

counter:
  camera_motion:
    name: "Camera Motion Counter"
    icon: mdi:alert
    initial: 0
    restore: True

automation:
  - alias: "Cameras - Motion"
    initial_state: True
    trigger:
      - platform: webhook
        webhook_id: "camera_motion"
        local_only: True
    condition:
      condition: template
      value_template: "{{ is_state('input_boolean.camera_motion_enabled', 'on') }}"
    action:
      # take a picture
      - action: script.camera_snapshot_notify
        data:
          camera_entity: "{{ trigger.json.camera }}"
          filename: "{{ trigger.json.camera }}.jpg"
          title: "{{ trigger.json.name }}"
          media_content_id: "media-source://camera/{{ trigger.json.camera }}"
      # update the counter
      - service: counter.increment
        target:
          entity_id: counter.camera_motion

  - alias: "Cameras - Reset Camera Events"
    initial_state: True
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: counter.reset
        target:
          entity_id: counter.camera_motion
      - service: shell_command.purge_camera_events