counter:
  camera_motion:
    name: "Camera Motion Counter"
    icon: mdi:alert
    initial: 0
    restore: True


automation:

  - alias: "Cameras - Motion Webhook"
    initial_state: True
    trigger:
      - platform: webhook
        webhook_id: "camera_driveway_motion"
        local_only: True
      - platform: webhook
        webhook_id: "camera_back_yard_motion"
        local_only: True
    condition:
      condition: template
      value_template: "{{ is_state('alarm_control_panel.alarm', 'armed_away') }}"
    action:
      - service: counter.increment
        target:
          entity_id: counter.camera_motion

  - alias: "Cameras - Motion Alert"
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: counter.camera_motion
        above: 2
    condition:
      condition: template
      value_template: "{{ is_state('alarm_control_panel.alarm', 'armed_away') }}"
    action:
      - service: notify.phones
        data_template:
          title: "Beach"
          message: "Motion detected!"
          data:
            url: "/lovelace/cameras"

  - alias: "Cameras - Reset Motion Counter"
    initial_state: True
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: counter.reset
        target:
          entity_id: counter.camera_motion