counter:
  camera_motion_front:
    name: "Front Yard Camera Motion Counter"
    icon: mdi:alert
    initial: 0
    restore: True
  camera_motion_back:
    name: "Back Yard Camera Motion Counter"
    icon: mdi:alert
    initial: 0
    restore: True


automation:

  - alias: Cameras - Front yard motion webhook
    initial_state: True
    trigger:
      - platform: webhook
        webhook_id: "camera_driveway_motion"
        local_only: True
      - platform: webhook
        webhook_id: "camera_front_deck_motion"
        local_only: True
    action:
      - service: counter.increment
        target:
          entity_id: counter.camera_motion_front

  - alias: Cameras - Back yard motion webhook
    initial_state: True
    trigger:
      - platform: webhook
        webhook_id: "camera_upstairs_deck_motion"
        local_only: True
      - platform: webhook
        webhook_id: "camera_back_yard_motion"
        local_only: True
    action:
      - service: counter.increment
        target:
          entity_id: counter.camera_motion_back

  - alias: Cameras - Motion Alert
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: counter.camera_motion_front
        above: 20
        variables:
          location: "Front"
      - platform: numeric_state
        entity_id: counter.camera_motion_back
        above: 2
        variables:
          location: "Back"
    action:
      - service: notify.phones
        data_template:
          title: "Beach"
          message: "{{ location }} motion detected!"
          data:
            url: "/lovelace/cameras"

  - alias: Cameras - Reset motion counter
    initial_state: True
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: counter.reset
        target:
          entity_id: counter.camera_motion_front
      - service: counter.reset
        target:
          entity_id: counter.camera_motion_back