shell_command:
  purge_camera_events: !secret purge_cameras_events_cmd

counter:
  camera_motion:
    name: "Camera Motion Counter"
    icon: mdi:alert
    initial: 0
    restore: True

input_boolean:
  camera_motion_enabled:
    name: "Camera Motion Alerts"
    icon: "mdi:robot"

automation:
  - alias: "Cameras - Motion"
    initial_state: True
    trigger:
      - platform: webhook
        webhook_id: "camera_motion"
        local_only: True
    condition:
      condition: template
      value_template: "{{ is_state('input_boolean.camera_motion_enabled', 'on') }}"
    action:
      # take a picture
      - service: camera.snapshot
        data:
          entity_id: "{{ trigger.json.camera }}"
          filename: "/config/www/cameras/{{ trigger.json.camera }}.jpg"
      # create a text response for that picture
      - action: google_generative_ai_conversation.generate_content
        data:
          prompt: !secret prompt_describe_image
          filenames:
            - "/config/www/cameras/{{ trigger.json.camera }}.jpg"
        response_variable: generated_content
      # send notification
      - service: notify.phones
        data_template:
          title: "{{ trigger.json.name }}"
          message: "{{ generated_content.text }}"
          data:
            image: "/local/cameras/{{ trigger.json.camera }}.jpg"
            url: "/lovelace/cameras"
      # update the counter
      - service: counter.increment
        target:
          entity_id: counter.camera_motion

  - alias: "Cameras - Reset Camera Events"
    initial_state: True
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: counter.reset
        target:
          entity_id: counter.camera_motion
      - service: shell_command.purge_camera_events