climate:
  - platform: intesishome
    username: !secret intensis_user
    password: !secret intensis_pass


sensor:
  - platform: template
    sensors:
      downstairs_temp:
        friendly_name: "Downstairs Temperature"
        value_template: "{{ state_attr('climate.downstairs', 'current_temperature') }}"
        unit_of_measurement: "°F"

      upstairs_temp:
        friendly_name: "Upstairs Temperature"
        value_template: "{{ state_attr('climate.upstairs', 'current_temperature') }}"
        unit_of_measurement: "°F"
        
      hvac_on:
        value_template: >
          {% set modes = ["heat_cool", "heat", "dry", "fan_only", "cool"] %}
          {% if states('climate.downstairs') in modes or states('climate.upstairs') in modes %}on{% else %}off{% endif %}


automation:
  - alias: Climate - Windows Open
    initial_state: True
    trigger:
      - platform: state
        entity_id: 
          - group.doors_and_windows
          - sensor.hvac_on
        to: "on"
        for: "00:30:00"
    condition:
      condition: state
      entity_id: group.doors_and_windows
      state: "on"
    action:
      - service: script.hvac_windows_open
          
  - alias: Climate - Error
    initial_state: True
    trigger:
      # if not updated in a day
      - platform: template
        value_template: '{{ (as_timestamp(now()) - as_timestamp(states.climate.downstairs.last_updated)) / 86400 }}'
      - platform: template
        value_template: '{{ (as_timestamp(now()) - as_timestamp(states.climate.upstairs.last_updated)) / 86400 }}'
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Beach House
          message: 'HVAC lost contact and is unreachable'
_