climate:
  - platform: intesishome
    username: !secret intensis_user
    password: !secret intensis_pass


sensor:
  - platform: template
    sensors:
      downstairs_temp:
        friendly_name: "Downstairs Temperature"
        value_template: "{{ states('sensor.downstairs_trisensor_temp')|round(0) }}"
        unit_of_measurement: "°F"

      upstairs_temp:
        friendly_name: "Upstairs Temperature"
        value_template: "{{ states('sensor.upstairs_trisensor_temp')|round(0) }}"
        unit_of_measurement: "°F"

      bathroom_floor_temp:
        friendly_name: "Bathroom Floor Temperature"
        value_template: "{{ state_attr('climate.bathroom_floor', 'current_temperature')|round(0) }}"
        unit_of_measurement: "°F"

      hvac_on:
        value_template: >
          {% set modes = ["heat_cool", "heat", "dry", "fan_only", "cool"] %}
          {% if states('climate.downstairs') in modes or states('climate.upstairs') in modes %}on{% else %}off{% endif %}


automation:
  - alias: Climate - Windows Open
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - group.doors_and_windows
          - sensor.hvac_on
        to: "on"
        for: "00:30:00"
    condition:
      condition: state
      entity_id: group.doors_and_windows
      state: "on"
    action:
      - service: script.climate_windows_open

  - alias: Climate - Offline
    initial_state: True
    trigger:
      - platform: time
        at: "09:00:00"
    condition:
      condition: or
      conditions:
        # if not updated in a day
        - condition: template
          value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.climate.downstairs.last_updated)) / 86400) > 1 }}"
        - condition: template
          value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.climate.upstairs.last_updated)) / 86400) > 1 }}"
    action:
      - service: notify.slack
        data:
          message: "HVAC is offline"
