climate:
  - platform: intesishome
    username: !secret intensis_user
    password: !secret intensis_pass


sensor:
  - platform: template
    sensors:
      downstairs_temp:
        friendly_name: "Downstairs Temperature"
        value_template: "{{ state_attr('climate.downstairs', 'current_temperature') }}"
        unit_of_measurement: "°F"

      upstairs_temp:
        friendly_name: "Upstairs Temperature"
        value_template: "{{ state_attr('climate.upstairs', 'current_temperature') }}"
        unit_of_measurement: "°F"


automation:
  - alias: Climate - Windows Open
    initial_state: True
    trigger:
      - platform: state
        entity_id: group.doors_and_windows
        to: "on"
        for: "00:05:00"
    action:
      service: script.hvac_windows_open