automation:
  - alias: "Energy - UPS Status Change"
    initial_state: True
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        to: "Online Battery Charging"
      - platform: state
        entity_id: sensor.ups_status
        to: "On Battery Battery Discharging"
    action:
      service: notify.mobile_app_jeffs_iphone
      data_template:
        title: "Home"
        message: "UPS changed to {{ trigger.to_state.state }}! Battery at {{ states('sensor.ups_battery_charge') }}%"