automation:
  - alias: Energy - UPS status change
    initial_state: True
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ups_status
    action:
      - service: notify.mobile_app_jeffs_iphone
        data_template:
          title: "Beach"
          message: "UPS changed from {{ trigger.from_state }} to {{ trigger.to_state }}! Battery at {{ states('sensor.ups_battery_charge') }}%"