light:
  # Overrides
  - platform: switch
    name: "Desk"
    entity_id: switch.desk

  - platform: switch
    name: "Hallway"
    entity_id: switch.hallway_light

  - platform: switch
    name: "Master Reading 1"
    entity_id: switch.master_reading_1

  - platform: switch
    name: "Front Door"
    entity_id: switch.front_door_lights

  - platform: switch
    name: "Front Deck"
    entity_id: switch.front_deck_lights

  - platform: switch
    name: "Back Stairs"
    entity_id: switch.back_stairs_light

  - platform: switch
    name: "Back Yard Left"
    entity_id: switch.back_lights_left

  - platform: switch
    name: "Back Yard Right"
    entity_id: switch.back_lights_right

  - platform: switch
    name: "Back Landscape"
    entity_id: switch.back_landscape

  - platform: switch
    name: "Upstairs Deck"
    entity_id: switch.upstairs_deck_lights

  # Groups
  - platform: group
    name: "Living Room"
    unique_id: living_room
    entities:
      - light.livingroom_1
      - light.livingroom_2

  - platform: group
    name: "Downstairs"
    unique_id: downstairs
    entities:
      - light.living_room
      - light.dining_table
      - light.recessed
      - light.picture
      - light.guest_bed
      - light.kitchen_sink
      - light.kitchen_cabinets
      - light.kitchen_lights
      - light.desk

  - platform: group
    name: "Upstairs"
    unique_id: upstairs
    entities:
      - light.hallway
      - light.bunk_bed
      - light.master_bedroom
      - light.master_reading_1
      - light.master_reading_2
      - light.master_wall

  - platform: group
    name: "Front Yard"
    unique_id: front_yard
    entities:
      - light.front_door
      - light.front_deck

  - platform: group
    name: "Back Yard"
    unique_id: back_yard
    entities:
      - light.back_yard_left
      - light.back_yard_right

  - platform: group
    name: "Outside"
    unique_id: outside
    entities:
      - light.front_yard
      - light.back_yard
      - light.upstairs_deck
      - light.back_landscape

  - platform: group
    name: "House"
    unique_id: house
    entities:
      - light.downstairs
      - light.upstairs
      - light.outside


binary_sensor:
  # Groups
  - platform: group
    name: "Doors and Windows"
    unique_id: doors_and_windows
    entities:
      - binary_sensor.bathroom_window
      - binary_sensor.driveway_window
      - binary_sensor.kitchen_window
      - binary_sensor.master_slider
      - binary_sensor.front_door
      - binary_sensor.kitchen_door
      - binary_sensor.bay_window_left
      - binary_sensor.bay_window_right
      - binary_sensor.downstairs_front_window_left
      - binary_sensor.downstairs_front_window_right

  - platform: group
    name: "Downstairs Front Windows"
    unique_id: downstairs_front_windows
    entities:
      - binary_sensor.downstairs_front_window_left
      - binary_sensor.downstairs_front_window_right
      
  - platform: group
    name: "Bay Windows"
    unique_id: bay_windows
    entities:
      - binary_sensor.bay_window_left
      - binary_sensor.bay_window_right


group:
  shade_automation:
    name: "Make It Less Bright"
    entities:
      - switch.vertical_toggle_control_downstairs_front_windows
      - switch.vertical_toggle_control_downstairs_side_windows
  shades:
    name: "Window Shades"
    entities:
      - cover.window_shade_1
      - cover.window_shade_2
      - cover.window_shade_3
      - cover.window_shade_4
      - cover.window_shade_5
      - cover.window_shade_6