light:
  # Overrides
  - platform: switch
    name: "Desk"
    entity_id: switch.desk

  - platform: switch
    name: "Hallway"
    entity_id: switch.hallway_light

  - platform: switch
    name: "Master Reading 1"
    entity_id: switch.master_reading_1

  - platform: switch
    name: "Master Reading 2"
    entity_id: switch.master_reading_2

  - platform: switch
    name: "Front Door"
    entity_id: switch.front_door_lights

  - platform: switch
    name: "Front Deck"
    entity_id: switch.front_deck_lights

  - platform: switch
    name: "Back Stairs"
    entity_id: switch.back_stairs_light

  - platform: switch
    name: "Back Yard Left"
    entity_id: switch.back_lights_left

  - platform: switch
    name: "Back Yard Right"
    entity_id: switch.back_lights_right

  - platform: switch
    name: "Back Landscape"
    entity_id: switch.back_landscape

  - platform: switch
    name: "Upstairs Deck"
    entity_id: switch.upstairs_deck_lights

  # Groups
  - platform: group
    name: "Living Room"
    unique_id: living_room
    entities:
      - light.livingroom_1
      - light.livingroom_2

  - platform: group
    name: "Front Yard"
    unique_id: front_yard
    entities:
      - light.front_door
      - light.front_deck

  - platform: group
    name: "Back Yard"
    unique_id: back_yard
    entities:
      - light.back_yard_left
      - light.back_yard_right

  - platform: group
    name: "House"
    unique_id: house
    entities:
      # downstairs
      - light.living_room
      - light.dining_table
      - light.recessed
      - light.kitchen_sink
      - light.kitchen_cabinets
      - light.kitchen_lights
      - light.desk
      - light.picture
      - light.guest_bed
      # upstairs
      - light.hallway
      - light.bunk_bed
      - light.master_bedroom
      - light.master_reading_1
      - light.master_reading_2
      - light.master_wall
      # outside
      - light.front_yard
      - light.back_yard
      - light.upstairs_deck
      - light.back_landscape

binary_sensor:
  # Groups
  - platform: group
    name: "Doors and Windows"
    device_class: door
    unique_id: doors_and_windows
    entities:
      - binary_sensor.front_door
      - binary_sensor.bay_window_left
      - binary_sensor.bay_window_right
      - binary_sensor.downstairs_front_window_left
      - binary_sensor.downstairs_front_window_right
      - binary_sensor.driveway_window
      - binary_sensor.bathroom_window
      - binary_sensor.kitchen_window
      - binary_sensor.kitchen_door
      - binary_sensor.master_slider

  - platform: group
    name: "Downstairs Front Windows"
    unique_id: downstairs_front_windows
    entities:
      - binary_sensor.downstairs_front_window_left
      - binary_sensor.downstairs_front_window_right
      
  - platform: group
    name: "Bay Windows"
    unique_id: bay_windows
    entities:
      - binary_sensor.bay_window_left
      - binary_sensor.bay_window_right

group:
  media_player_speakers_and_tvs:
    name: "Speakers and TVs"
    icon: "mdi:television"
    entities:
      # speakers
      - media_player.back_speakers
      - media_player.front_speakers
      - media_player.kitchen_speakers
      - media_player.living_room_speakers
      - media_player.master_bedroom_speakers
      - media_player.upstairs_deck_speakers
      - media_player.master_bedroom_wifi
      - media_player.bunk_bedroom_wifi
      # tvs
      - media_player.downstairs_apple_tv
      - media_player.master_bedroom_apple_tv
      - media_player.bunk_bed_apple_tv

  climate:
    name: "Climate"
    entities:
      - climate.downstairs
      - climate.upstairs

  shade_automation:
    name: "Make It Less Bright"
    icon: mdi:creation
    entities:
      - switch.vertical_toggle_control_downstairs_front_windows
      - switch.vertical_toggle_control_downstairs_side_windows

  shades:
    name: "Window Shades"
    icon: mdi:window-closed-variant
    entities:
      - cover.window_shade_1
      - cover.window_shade_2
      - cover.window_shade_3
      - cover.window_shade_4
      - cover.window_shade_5
      - cover.window_shade_6