light:
  - platform: group
    name: Living Room
    entities:
      # node 10
      - light.livingroom_1
      # node 8
      - light.livingroom_2


group:
  downstairs_lights:
    entities:
      - light.living_room
      # node 12
      - light.dining_table
      # node 11
      - light.recessed
      # node 9
      - light.picture
      # node 14
      - light.guest_bed
      # node 15
      - light.kitchen_sink
      # node 16
      - light.kitchen_cabinets
      # node 18
      - light.kitchen_lights
      # node 17
      - switch.desk
  upstairs_lights:
    entities:
      # node 19
      - light.hallway_chandelier
      # node 21
      - light.bunk_bed
      # node 25
      - light.master_bedroom
      # node 23
      - light.master_reading_1
      # node 22
      - light.master_reading_2
      # node 26
      - light.master_wall
      # node 24
      - switch.master_wall_outlet
  outside_lights:
    entities:
      - group.front_lights
      - group.back_lights
      # node 3
      - switch.back_twinkle_lights
      # node 28
      - switch.back_stairs_light
      # node 27
      - switch.upstairs_deck_lights
  front_lights:
    name: Front Lights
    entities:
      # node 20
      - switch.front_door_lights
      # node 4
      - switch.front_deck_lights
  back_lights:
    name: Back Lights
    entities:
      # node 5
      - switch.back_lights_left
      # node 6
      - switch.back_lights_right
  lights:
    entities:
      - group.downstairs_lights
      - group.upstairs_lights
      - group.outside_lights


automation:
  - alias: Lights - House off after sunrise
    initial_state: True
    trigger:
      platform: time
      at: "08:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_off

  - alias: Lights - Automatic front lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -4 }}"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.front_door_lights

  - alias: Lights - Automatic back lights
    initial_state: True
    trigger:
      - platform: sun
        event: sunset
        offset: "01:00:00"
      - platform: time
        at: "21:00:00"
    condition:
      - condition: state
        entity_id: alarm_control_panel.abode_alarm
        state: "disarmed"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.back_twinkle_lights

  - alias: Lights - Automatic outside lights off
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - group.front_lights
          - group.back_lights
        to: "on"
        for:
          hours: 1
    action:
      - service: homeassistant.turn_off
        data_template:
          entity_id: 
            - group.front_lights
            - group.back_lights