automation:
  - alias: Lights - House off after sunrise
    initial_state: True
    trigger:
      platform: time
      at: "08:30:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_off

  - alias: Lights - Automatic front lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -4 }}"
    action:
      - service: homeassistant.turn_on
        entity_id: light.front_door

  - alias: Lights - Automatic back lights
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        offset: "00:30:00"
      # off
      - platform: time
        at: "22:00:00"
    condition:
      - condition: state
        entity_id: alarm_control_panel.abode_alarm
        state: "disarmed"
    action:
      - service_template: >
          homeassistant.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: light.twinkle_lights

  - alias: Lights - Automatic outside lights off
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - light.front_yard
          - light.back_yard
        to: "on"
        for:
          hours: 1
    action:
      - service: homeassistant.turn_off
        data_template:
          entity_id: 
            - light.front_yard
            - light.back_yard
            
  - alias: Lights - Double tap kitchen for twinkle lights
    initial_state: True
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 18
    action:
      - service_template: >
          homeassistant.turn_{% if trigger and trigger.event.data["value"] == 255 %}on{% else %}off{% endif %}
        entity_id: light.twinkle_lights

  - alias: Lights - Double tap master bedroom light
    initial_state: True
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 25
    action:
      - service_template: >
          homeassistant.turn_{% if trigger and trigger.event.data["value"] == 255 %}on{% else %}off{% endif %}
        entity_id: light.master_wall


  - alias: Lights - Double tap front door light
    initial_state: True
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 20
    action:
      - service_template: >
          homeassistant.turn_{% if trigger and trigger.event.data["value"] == 255 %}on{% else %}off{% endif %}
        entity_id: light.front_deck
