automation:
  - alias: Lights - House off after sunrise
    initial_state: True
    trigger:
      platform: time
      at: "08:30:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_off

  - alias: Lights - Automatic front lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -4 }}"
    action:
      - service: homeassistant.turn_on
        entity_id: light.front_yard

  - alias: Lights - Automatic outside lights off
    initial_state: True
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: homeassistant.turn_off
        data_template:
          entity_id: 
            - light.front_yard
            - light.back_yard
            
  - alias: Lights - Double tap 
    initial_state: True
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 20
        variables:
          entity: "front_deck"
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 25
        variables:
          entity: "master_wall"
    action:
      - data_template:
          entity_id: light.{{ entity }}
        service_template: homeassistant.turn_{% if trigger.event.data["value"] == 255 %}on{% else %}off{% endif %}   

  - alias: Lights - Landscape
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        offset: "00:15:00"
        variables:
          action: "turn_on"
      # off
      - platform: time
        at: "23:00:00"
        variables:
          action: "turn_off"
    condition:
      condition: template
      value_template: "{{ is_state('alarm_control_panel.alarm', 'disarmed') }}"
    action:
      - service: >
          switch.{{ action }}
        entity_id:
          - switch.back_landscape