light:
  - platform: group
    name: Living Room
    entities:
      - light.livingroom_1
      - light.livingroom_2


group:
  downstairs_lights:
    entities:
      - light.living_room
      - light.dining_table
      - light.mood
      - light.picture
      - light.guest_bed
      - light.kitchen_sink
      - light.kitchen_cabinets
      - light.kitchen_lights
      - switch.desk
  upstairs_lights:
      - light.hallway_chandelier
      - light.bunk_bed
      - light.master_bedroom
      - light.master_reading_1
      - light.master_reading_2
      - light.master_wall_lights
      - switch.master_wall_outlet
  outside_lights:
    entities:
      - switch.front_door_lights
      - switch.front_deck_lights
      - switch.back_lights_left
      - switch.back_lights_right
      - switch.back_twinkle_lights
      - switch.back_stairs_light
      - switch.upstairs_deck_lights
  lights:
      - group.downstairs_lights
      - group.upstairs_lights
      - group.outside_lights



automation:
  - alias: Lights - Automatic front lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -4 }}"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.front_door_lights

  - alias: Lights - Automatic back lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "on"
    condition:
      condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -4 }}"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.back_lights_right

  - alias: Lights - Automatic outside lights off
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - group.outside_lights
        to: "on"
        for:
          hours: 1
    action:
      - service: homeassistant.turn_off
        data_template:
          entity_id: group.outside_lights

  - alias: Lights - Off after sunrise
    initial_state: True
    trigger:
      platform: time
      at: "08:00:00"
    condition:
      condition: state
      entity_id: group.lights
      state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.lights

  - alias: Lights - Tree
    trigger:
      - platform: sun
        event: sunset
      - platform: time
        at: "22:00:00"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.zooz_plug
