light:
  - platform: group
    name: Living Room
    entities:
      - light.livingroom_1
      - light.livingroom_2


group:
  downstairs_lights:
    entities:
      - light.living_room
      - light.dining_table
      - light.recessed
      - light.picture
      - light.guest_bed
      - light.kitchen_sink
      - light.kitchen_cabinets
      - light.kitchen_lights
      - switch.desk
  upstairs_lights:
    entities:
      - light.hallway
      - light.bunk_bed
      - light.master_bedroom
      - light.master_reading_1
      - light.master_reading_2
      - light.master_wall
      - switch.master_wall_outlet
  outside_lights:
    entities:
      - group.front_lights
      - group.back_lights
      - switch.back_twinkle_lights
      - switch.back_stairs_light
      - switch.upstairs_deck_lights
  front_lights:
    name: Front Lights
    entities:
      - switch.front_door_lights
      - switch.front_deck_lights
  back_lights:
    name: Back Lights
    entities:
      - switch.back_lights_left
      - switch.back_lights_right
  lights:
    entities:
      - group.downstairs_lights
      - group.upstairs_lights
      - group.outside_lights


automation:
  - alias: Lights - House off after sunrise
    initial_state: True
    trigger:
      platform: time
      at: "08:30:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_off

  - alias: Lights - Automatic front lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -4 }}"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.front_door_lights

  - alias: Lights - Automatic back lights
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        offset: "00:30:00"
      # off
      - platform: time
        at: "23:00:00"
    condition:
      - condition: state
        entity_id: alarm_control_panel.abode_alarm
        state: "disarmed"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.back_twinkle_lights

  - alias: Lights - Automatic outside lights off
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - group.front_lights
          - group.back_lights
        to: "on"
        for:
          hours: 1
    action:
      - service: homeassistant.turn_off
        data_template:
          entity_id: 
            - group.front_lights
            - group.back_lights
            
  - alias: Lights - Double tap kitchen for twinkle lights
    initial_state: True
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 18
    action:
      - service_template: >
          homeassistant.turn_{% if trigger and trigger.event.data["value"] == 255 %}on{% else %}off{% endif %}
        entity_id: switch.back_twinkle_lights

  - alias: Lights - Double tap master bedroom for wall lights
    initial_state: True
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 25
    action:
      - service_template: >
          homeassistant.turn_{% if trigger and trigger.event.data["value"] == 255 %}on{% else %}off{% endif %}
        entity_id: light.master_wall
