light:
  - platform: group
    name: Living Room
    entities:
      - light.living_room_1
      - light.living_room_2
  - platform: group
    name: Master Reading Lights
    entities:
      - light.master_reading_light_1
      - light.master_reading_light_2


group:
  frontyard_lights:
    - switch.front_door
    - switch.front_deck
  backyard_lights:
    name: Backyard
    entities:
      - switch.backyard_lights_left
      - switch.backyard_lights_right
  lights:
      - light.living_room
      - light.dining_lights
      - light.mood_lights
      - light.picture_lights
      - switch.desk_light
      - light.guest_bedroom
      - light.sink
      - light.cabinets
      - light.kitchen
      - light.hallway
      - light.master
      - light.master_reading_light_1
      - light.master_reading_light_2
      - light.master_wall_lights
      - light.bunk_bedroom
      - group.frontyard_lights
      - group.backyard_lights
      - switch.twinkle_lights
      - switch.backyard_stairs
      - switch.upstairs_deck


automation:
  - alias: Lights - Automatic front lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < -4 }}'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.front_door

  - alias: Lights - Automatic back lights
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_door
        to: "on"
    condition:
      condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < -4 }}'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.backyard_lights_right

  - alias: Lights - Turn off after sunrise
    initial_state: True
    trigger:
      platform: sun
      event: sunrise
      offset: '+01:00:00'
    condition:
      condition: state
      entity_id: group.lights
      state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.lights