automation:
  - alias: Alarm - Turn house on
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode_alarm
      from: "armed_away"
      to: "disarmed"
    action:
      - service: script.turn_on
        entity_id: script.welcome_home

  - alias: Alarm - Turn house off
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: "armed_away"
    action:
      - service: script.turn_on
        entity_id: script.goodbye

  - alias: Alarm - Notifications
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.abode_alarm
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Beach House
          message: >
            {% if states("alarm_control_panel.abode_alarm", "armed_home") %}
              Alarm armed home
            {% elif states("alarm_control_panel.abode_alarm", "armed_away") %}
              Alarm armed away
            {% elif states("alarm_control_panel.abode_alarm", "disarmed") %}
              Alarm off
            {% endif %}

  - alias: Alarm - Alert
    initial_state: True
    trigger:
      platform: event
      event_type: abode_alarm
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Beach House
          message: "Alarm is going off!"

  - alias: Alarm - Fault
    initial_state: True
    trigger:
      - platform: event
        event_type: abode_panel_fault
      - platform: event
        event_type: abode_panel_restore
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Beach House
          message: "Alarm {{ trigger.event.data.event_name }}"
