abode:
  username: !secret abode_user
  password: !secret abode_pass


automation:
  - alias: Alarm - Turn house on
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode_alarm
      from: "armed_away"
      to: "disarmed"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.living_room
          - light.kitchen
          - switch.front_door
      - service: script.turn_on
        entity_id: script.shades_up      

  - alias: Alarm - Turn house off
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: "armed_away"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - light.living_room
          - light.dining_lights
          - light.mood_lights
          - light.picture_lights
          - switch.desk_light
          - light.guest_bedroom
          - light.sink
          - light.cabinets
          - light.kitchen
          - light.hallway
          - light.master
          - light.master_reading_light_1
          - light.master_reading_light_2
          - light.master_wall_lights
          - light.bunk_bedroom
          - switch.front_door
          - switch.front_deck
          - switch.backyard_lights_left
          - switch.backyard_lights_right
          - switch.twinkle_lights
          - switch.backyard_stairs
          - switch.upstairs_deck
      - service: script.turn_on
        entity_id: script.shades_down

  - alias: Alarm - Notifications
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.abode_alarm
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Beach House
          message: >
            {% if states.alarm_control_panel.abode_alarm.state == "armed_home" %}
              Alarm armed home
            {% elif states.alarm_control_panel.abode_alarm.state == "armed_away" %}
              Alarm armed away
            {% else %}
              Alarm off
            {% endif %}

  - alias: Alarm - Alert
    initial_state: True
    trigger:
      platform: event
      event_type: abode_alarm
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Beach House
          message: "Alarm is going off!"

  - alias: Alarm - Fault
    initial_state: True
    trigger:
      - platform: event
        event_type: abode_panel_fault
      - platform: event
        event_type: abode_panel_restore
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Beach House
          message: "Alarm {{ trigger.event.data.event_name }}"
