binary_sensor:
  - platform: tod
    name: Morning
    after: "05:00"
    before: "09:00"
    
  - platform: tod
    name: Day
    after: "09:00"
    before: sunset
    before_offset: "01:00"
    
  - platform: tod
    name: Night
    after: sunset
    after_offset: "01:00"
    before: "05:00"

input_boolean:
  night_mode:
    initial: false

shell_command:
  purge_backups: "find ./backups -maxdepth 1 -name '*.tar' -type f -mtime +365 -delete"

automation:
  - alias: System - Backup
    initial_state: True
    trigger:
      platform: time
      at: "01:00:00"
    condition:
      condition: template
      value_template: "{{ now().day == 1 }}"
    action:
      - service: backup.create
      - service: shell_command.purge_backups

  - alias: System - UI theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  - alias: System - Night mode reset
    initial_state: True
    trigger:
      platform: time
      at: "09:00:00"
    action:
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night_mode

  - alias: System - Trash reminder
    initial_state: True
    trigger:
      platform: time
      at: "18:00:00"
    condition:
    - condition: time
      weekday:
        - thu
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: "disarmed"
    action:
      - service: notify.phones
        data:
          title: "Beach"
          message: "Put the trash cans out"

  - alias: System - Entity health check
    initial_state: True
    trigger:
      platform: time
      at: "04:00:00"
      variables:
         unhealthy: "{{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'dead', 'none']) | list | map(attribute='name') | join(', ') }}"
    action:
      - if:
          condition: template
          value_template: "{{ unhealthy | length > 0 }}"
        then:
          service: persistent_notification.create
          data:
            notification_id: unhealthy
            message: "The following are unavailable: {{ unhealthy }}"