automation:
  - alias: System - Theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: clear

  - alias: System - Low battery check
    initial_state: True
    trigger:
      platform: time
      at: "00:00:00"
    condition:
      condition: template
      value_template: >
        {% for zwave in states.zwave if zwave.attributes.battery_level %}
          {%- if zwave.attributes.battery_level|int < 20 -%}
            {{ true }}
          {%- endif -%}
        {%- endfor -%}
    action:
      - service: notify.jeffs_phone
        data_template:
          message: >
            {% for zwave in states.zwave if zwave.attributes.battery_level %}
              {%- if zwave.attributes.battery_level|int < 20 -%}
                {{ zwave.attributes.friendly_name }} needs new batteries.
              {%- endif -%}
            {%- endfor -%}