google:
  client_id: !secret google_id
  client_secret: !secret google_secret

binary_sensor:
  - platform: tod
    name: Morning
    after: "04:00"
    before: "12:00"
  - platform: tod
    name: Evening
    after: "12:00"
    before: "04:00"

automation:
  - alias: System - UI home image
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/2"
    action:
      - service: camera.snapshot
        data:
          entity_id:
            - camera.beach
          filename: /config/www/cameras/beach.png

  - alias: System - UI theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: clear

  - alias: System - Calendar alerts
    initial_state: True
    trigger:
      - platform: state
        entity_id: calendar.beach_house
        to: "on"
      - platform: state
        entity_id: calendar.beach_house
        to: "off"
    action:
      - service: notify.jeff_and_jillians_phone
        data_template:
          title: Beach House
          message: >
            REMINDER: {% if trigger and trigger.to_state == "on" %}Disarm{% else %}Arm{% endif %} the alarm.
            EVENT: {{ state_attr('calendar.beach_house', 'message') }}

  - alias: System - Low battery check
    initial_state: True
    trigger:
      platform: time
      at: "00:00:00"
    condition:
      condition: template
      value_template: >
        {% for zwave in states.zwave if zwave.attributes.battery_level %}
          {%- if zwave.attributes.battery_level|int < 20 -%}
            {{ true }}
          {%- endif -%}
        {%- endfor -%}
    action:
      - service: notify.jeffs_phone
        data_template:
          message: >
            {% for zwave in states.zwave if zwave.attributes.battery_level %}
              {%- if zwave.attributes.battery_level|int < 20 -%}
                {{ zwave.attributes.friendly_name }} needs new batteries.
              {%- endif -%}
            {%- endfor -%}