google:
  client_id: !secret google_id
  client_secret: !secret google_secret

binary_sensor:
  - platform: tod
    name: Morning
    after: "05:00"
    before: "09:00"
    
  - platform: tod
    name: Day
    after: "09:00"
    before: sunset
    before_offset: "01:00"
    
  - platform: tod
    name: Night
    after: sunset
    after_offset: "01:00"
    before: "05:00"

automation:
  - alias: System - UI home image
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/2"
    action:
      - service: camera.snapshot
        data_template:
          entity_id:
            - camera.{% if states('binary_sensor.night') == 'on' %}front_deck{% else %}beach{% endif %}
          filename: /config/www/cameras/home.png

  - alias: System - UI theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: clear

  - alias: System - Snapshot sunrise
    initial_state: True
    trigger:
      - platform: sun
        event: sunrise
        offset: "-00:10:00"
      - platform: sun
        event: sunrise
        offset: "00:10:00"
    action:
      - service: camera.snapshot
        data:
          entity_id:
            - camera.beach
          filename: /config/www/cameras/sunrise/{{ now().strftime("%Y%m%d-%H%M%S") }}.png

  - alias: System - Snapshot sunset
    initial_state: True
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:10:00"
      - platform: sun
        event: sunset
        offset: "00:10:00"
    action:
      - service: camera.snapshot
        data:
          entity_id:
            - camera.beach
          filename: /config/www/cameras/sunsets/{{ now().strftime("%Y%m%d-%H%M%S") }}.png

  - alias: System - Calendar alerts
    initial_state: True
    trigger:
      - platform: state
        entity_id: calendar.beach_house
        to: "on"
      - platform: state
        entity_id: calendar.beach_house
        to: "off"
    action:
      - service: notify.jeff_and_jillians_phone
        data_template:
          title: Beach House
          message: >
            REMINDER: {% if trigger and trigger.to_state == "on" %}Disarm{% else %}Arm{% endif %} the alarm.
            EVENT: {{ state_attr('calendar.beach_house', 'message') }}