automation:
  - alias: "System - Theme"
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: app_theme

  - alias: "System - Reset settings"
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      to: "armed_away"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - automation.lights_automatic_outside_lights
          - automation.climate_windows_open

  - alias: "System - Reset Speakers"
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      to: "armed_away"
    action:
      - service: media_player.volume_set
        target:
          entity_id: 
            - media_player.kitchen_display
        data:
          volume_level: 0.6
      # some speakers should be quieter
      - service: media_player.volume_set
        target:
          entity_id: 
            - media_player.master_bedroom_wifi
            - media_player.bunk_bedroom_wifi
        data:
          volume_level: 0.5

  - alias: "System - Refresh Apple TVs"
    initial_state: True
    mode: parallel
    trigger:
      platform: state
      entity_id: 
        - media_player.downstairs_apple_tv
        - media_player.bunk_bed_apple_tv
        - media_player.master_bedroom_apple_tv
      to: "unavailable"
      for:
        minutes: 1
    actions:
      - action: homeassistant.reload_config_entry
        target:
          entity_id: "{{ trigger.entity_id }}"
      - action: notify.mobile_app_jeffs_iphone
        data:
          message: "Resetting {{ trigger.entity_id }}"


  - alias: "System - Trash Reminder"
    initial_state: True
    trigger:
      platform: time
      at: "18:00:00"
    condition:
    - condition: time
      weekday:
        - thu
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: "disarmed"
    action:
      - service: notify.phones
        data:
          title: "Beach"
          message: "Put the trash cans out"

  - alias: "System - Health Check"
    initial_state: False
    trigger:
      platform: time
      at: "04:00:00"
      variables:
         unhealthy: "{{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'dead', 'none']) | list | map(attribute='name') | join(', ') }}"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - if:
          condition: template
          value_template: "{{ unhealthy | length > 0 }}"
        then:
          service: persistent_notification.create
          data:
            notification_id: unhealthy
            message: "The following are unavailable: {{ unhealthy }}"