binary_sensor:
  - platform: tod
    name: Morning
    after: "05:00"
    before: "09:00"
    
  - platform: tod
    name: Day
    after: "09:00"
    before: sunset
    before_offset: "01:00"
    
  - platform: tod
    name: Night
    after: sunset
    after_offset: "01:00"
    before: "05:00"

input_boolean:
  night_mode:
    initial: false

automation:
  - alias: System - UI theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  - alias: System - Night mode reset
    initial_state: True
    trigger:
      platform: time
      at: "09:00:00"
    action:
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night_mode

#   - alias: System - Reset speaker volumes
#     initial_state: True
#     trigger:
#       platform: time
#       at: "06:00:00"
#     action:
#       - service: media_player.volume_set
#         target:
#           entity_id: media_player.kitchen_display
#         data:
#           volume_level: 0.6

  - alias: System - Trash reminder
    initial_state: True
    trigger:
      platform: time
      at: "18:00:00"
    condition:
    - condition: time
      weekday:
        - thu
    - condition: state
      entity_id: alarm_control_panel.abode_alarm
      state: "disarmed"
    action:
      - service: notify.phones
        data:
          title: "Beach"
          message: "Put the trash cans out"