shell_command:
  purge_backups: !secret purge_backups_cmd

automation:
  - alias: "System - Backup"
    initial_state: True
    trigger:
      platform: time
      at: "01:00:00"
    condition:
      condition: template
      value_template: "{{ now().day == 1 }}"
    action:
      - service: backup.create
      - service: shell_command.purge_backups

  - alias: "System - Theme"
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  - alias: "System - Reset Speakers"
    initial_state: True
    trigger:
      platform: time
      at: "12:00:00"
    action:
      - service: media_player.volume_set
        target:
          entity_id: 
            - media_player.kitchen_display
        data:
          volume_level: 0.6
      # some speakers should be quieter
      - service: media_player.volume_set
        target:
          entity_id: 
            - media_player.master_bedroom_mini
            - media_player.bunk_bedroom_wifi
        data:
          volume_level: 0.5

  - alias: "System - Trash Reminder"
    initial_state: True
    trigger:
      platform: time
      at: "18:00:00"
    condition:
    - condition: time
      weekday:
        - thu
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: "disarmed"
    action:
      - service: notify.phones
        data:
          title: "Beach"
          message: "Put the trash cans out"

  - alias: "System - Health Check"
    initial_state: True
    trigger:
      platform: time
      at: "04:00:00"
      variables:
         unhealthy: "{{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'dead', 'none']) | list | map(attribute='name') | join(', ') }}"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - if:
          condition: template
          value_template: "{{ unhealthy | length > 0 }}"
        then:
          service: persistent_notification.create
          data:
            notification_id: unhealthy
            message: "The following are unavailable: {{ unhealthy }}"