binary_sensor:
  - platform: tod
    name: Morning
    after: "05:00"
    before: "09:00"
    
  - platform: tod
    name: Day
    after: "09:00"
    before: sunset
    before_offset: "01:00"
    
  - platform: tod
    name: Night
    after: sunset
    after_offset: "01:00"
    before: "05:00"

input_boolean:
  night_mode:
    initial: false

automation:
  - alias: System - UI theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home