sun:

sensor:
#   - platform: noaa_tides
#     name: Tides
#     station_id: !secret noaa_station

  - platform: template
    sensors:
      outside_temp: 
        value_template: >
          {{ states('sensor.c9585_temperature')|round(0, default=0) }}°F

      outside_forecast:
        value_template: >
          {% set weather = state_attr('weather.c9585_daynight', 'forecast') %}
          {% set today = weather[0] %}

          {%- if today and today.detailed_description -%}
            {{ today.detailed_description.split('.')[0]|lower }}
          {%- endif %}
        icon_template: >
          {% set condition = today and today.condition %}
          
          {%- if "cloud" in weather -%}
            mdi:weather-cloudy
          {%- elif "fog" in weather -%}
            mdi:weather-fog
          {%- elif "rain" in weather -%}
            mdi:umbrella-outline
          {%- elif "wind" in weather -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}