sensor:
  - platform: noaa_tides
    station_id: 9413745
    name: tides
    type: tides

  - platform: noaa_tides
    station_id: 9413450
    type: temp
    name: water_temp
    
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - hourly_summary
      - temperature
      - humidity
      - uv_index
      - wind_speed
      - wind_gust