sun:

sensor:
  - platform: noaa_tides
    station_id: 9413616

  - platform: template
    sensors:
      outside_temp: 
        value_template: >
          {% set forecast = state_attr('weather.kmry_daynight', 'forecast') %}

          {% if forecast %}
            {{ forecast[0].temperature|round(0) }}
          {% endif %}

      outside_forecast:
        value_template: >
          {% set forecast = state_attr('weather.kmry_daynight', 'forecast') %}

          {% if forecast %}
            {% set description = forecast[0].detailed_description %}
            {% set value = description.split('.')[0]|lower %}
          {% endif %}

          {{ value|default('') }}
        icon_template: >
          {% set forecast = state_attr('weather.kmry_daynight', 'forecast') %}

          {% if forecast %}
            {% set condition = forecast[0].condition %}
          {% else %}
            {% set condition = '' %}
          {% endif %}
          
          {%- if "cloud" in condition -%}
            mdi:weather-cloudy
          {%- elif "fog" in condition -%}
            mdi:weather-fog
          {%- elif "rain" in condition -%}
            mdi:umbrella-outline
          {%- elif "wind" in condition -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}