sensor:
  - platform: magicseaweed
    api_key: !secret magic_seaweed_key
    name: Manresa
    spot_id: 258
    monitored_conditions:
      - swell_forecast
      - max_breaking_swell
      
  - platform: noaa_tides
    station_id: 9413745

  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - hourly_summary
      - temperature
      - humidity
      - uv_index
      - wind_speed
      - wind_gust

  - platform: template
    sensors:
      stars:
        friendly_name: "Stars"
        value_template: "{{ state_attr('sensor.current_manresa_max', 'stars') }}"

      swell_direction:
        friendly_name: "Swell Direction"
        value_template: "{{ state_attr('sensor.current_manresa_max', 'swell_direction') }}"
        
      swell_period:
        friendly_name: "Swell Period"
        value_template: "{{ state_attr('sensor.current_manresa_max', 'swell_period') }}"

      wind_speed:
        friendly_name: "Wind Speed"
        value_template: "{{ state_attr('sensor.current_manresa_max', 'wind_speed') }}"
        
      wind_gusts:
        friendly_name: "Wind Gusts"
        value_template: "{{ state_attr('sensor.current_manresa_max', 'wind_gusts') }}"
