sensor:
  - platform: noaa_tides
    name: Tides
    station_id: !secret noaa_station

  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - hourly_summary
      - temperature
      - humidity
      - uv_index
      - wind_speed
      - wind_gust