sun:

rest:
  - authentication: basic
    scan_interval: 3600
    resource_template: "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions&station=9413616&datum=MLLW&time_zone=lst_ldt&units=english&interval=hilo&format=json&begin_date={{ now().strftime('%Y%m%d') }}&end_date={{ (as_timestamp(now())+ 86400) | timestamp_custom('%Y%m%d') }}"
    sensor:
      - name: "Current Tide"
        value_template: >
          {% set current = as_timestamp(now()) %}
          {% set tide = namespace(current=False) %}

          {% for prediction in value_json.predictions | reverse %}
            {% if not tide.current %}
              {% if as_timestamp(prediction.t) < current %}
                {% if prediction.type == 'H' %}High{% else %}Low{% endif %} tide {{ prediction.v | round(1) }}' at {{ as_timestamp(prediction.t) | timestamp_custom('%-I:%M %p') }}
                {% set tide.current = True %}
              {% endif %}
            {% endif %}
          {% endfor %}

      - name: "Next Tide"
        value_template: >
          {% set current = as_timestamp(now()) %}
          {% set tide = namespace(next=False) %}

          {% for prediction in value_json.predictions %}
            {% if not tide.next %}
              {% if as_timestamp(prediction.t) > current %}
                {% if prediction.type == 'H' %}High{% else %}Low{% endif %} tide {{ prediction.v | round(1) }}' at {{ as_timestamp(prediction.t) | timestamp_custom('%-I:%M %p') }}
                {% set tide.next = True %}
              {% endif %}
            {% endif %}
          {% endfor %}

      - name: "Tides"
        value_template: "OK"
        json_attributes:
          - "predictions"

sensor:
  - platform: template
    sensors:
      outside_temp: 
        unit_of_measurement: "°F"
        value_template: >
          {% set forecast = state_attr('weather.kmry_daynight', 'forecast') %}

          {% if forecast %}
            {{ forecast[0].temperature|round(0) }}
          {% endif %}

      outside_forecast:
        value_template: >
          {% set forecast = state_attr('weather.kmry_daynight', 'forecast') %}

          {% if forecast %}
            {% set description = forecast[0].detailed_description %}
            {% set value = description.split('.')[0]|lower %}
          {% endif %}

          {{ value|default('') }}
        icon_template: >
          {% set forecast = state_attr('weather.kmry_daynight', 'forecast') %}

          {% if forecast %}
            {% set condition = forecast[0].condition %}
          {% else %}
            {% set condition = '' %}
          {% endif %}
          
          {%- if "cloud" in condition -%}
            mdi:weather-cloudy
          {%- elif "fog" in condition -%}
            mdi:weather-fog
          {%- elif "rain" in condition -%}
            mdi:umbrella-outline
          {%- elif "wind" in condition -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}