sun:

sensor:
  - platform: template
    sensors:
      outside_temp: 
        value_template: >
          {{ states('sensor.c9585_temperature')|round(0, default=0) }}°F

      outside_forecast:
        value_template: >
          {% set weather = state_attr('weather.c9585_daynight', 'forecast') %}
          
          {% if weather %}
          {% set today = weather[0] %}
          {% endif %}

          {%- if today -%}
            {{ today.detailed_description.split('.')[0]|lower }}
          {%- endif %}
        icon_template: >
          {% if today %}
          {% set condition = today.condition %}
          {% endif %}
          
          {%- if "cloud" in condition -%}
            mdi:weather-cloudy
          {%- elif "fog" in condition -%}
            mdi:weather-fog
          {%- elif "rain" in condition -%}
            mdi:umbrella-outline
          {%- elif "wind" in condition -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}